### ISSUE TITLE
Email address not available

### ISSUE THREAD

**Issue by aryakarani** [je-suis-tm/je-suis-tm#1]
Hello TM,

I wanted to reach you but the email address on your website is apparently invalid.

Thanks,
Arya.

**Comment by je-suis-tm** [comment]
Arya, sorry for the late reply, how can I help?

**Comment by aryakarani** [comment]
Hello TM,
I am a recent Mechatronics engineering graduate from Mumbai, India with a
background in AI-Robotics, I recently stumbled upon your amazing repository
and page. I would like to know more about you and this page. I have wanted
to make a career shift from Robotics Software to Fintech and algorithmic
trading but I am a bit lost on how to get started on implementation as the
resources available on the internet are so vast and yet inconclusive. I
would love to know more about you and how you built your whole repository
and what you learnt to get there also I would love to know about any
industry experience you have and skills I need to procure to become
industry relevant in this field.

It’s amazing to see such good open-source projects and I definitely look
forward to learning anything from you.

Thanks and Regards,
Arya Karani.

**Comment by je-suis-tm** [comment]
Arya, I am a bit flattered by what you said but thx for the compliment. 

About the repositories, obviously Rome wasn’t built in a day. What you see is years of workings. If you check the code across the timeline, you will see how bad I used to code versus now. You have to take your time and be patient to get everything right. For instance, Cathie Wood didn’t make her name before her 60s. 

As for how I got there, my only advice is enthusiasm. I am genuinely passionate about what I do. That’s what motivates me to waste countless hours to try different things. Things definitely go wrong along the way. You only stick around because you are keen to see things done. It’s the only energy to keep you on a steep learning curve.

I didn’t start out with a plan. The original purpose (probably still the same) of this GitHub page was merely to document the things I did in case someday I lost touch and had to reinvent the wheel. Start with a baby step even if it sounds really stupid (like a code to compute moving average). Your coding and knowledge will improve over time and you will be more confident and capable of working on big projects.

I cannot really advise you on what to learn. Since you want to pivot to quantitative trading, you should know it still covers front office (trading quant), mid office (risk quant) and back office (research quant). Each area requires different skillsets and knowledges. Overall, you need good understanding of statistics (range from stochastic calculus to machine learning), great level of coding (more than calling functions in packages) and some basic ideas of finance (market microstructure, pricing mechanism, etc). You come from robotics background so I assume your statistics and coding should be fair. To gain more exposure to finance, there are two paths – CFA or a master degree (preferably financial mathematics or engineering). I come from stat+econ background. Some academic knowledges come in handy but many things still need to be learnt from the job.

That’s just my two cents. Good luck!

**Comment by aryakarani** [comment]
Hello TM,

Thank you so much for all the guidance. Would you help me with a recommendation of a book/course that you think covers stochastic calculus and machine learning from a quantitative perspective or any material you find to be exceptionally helpful now or in your early days.

Thanks and Best Regards,
Arya Karani.

**Comment by je-suis-tm** [comment]
Well, for machine learning, Andrew Ng's lecture is undisputedly the most famous. Many people including me started there so that's what I would recommend. You can snoop around my machine learning to find any additional useful algorithms Andrew Ng doesn't cover.

As for stochastic calculus, I learned it from school so I cannot really recommend a good textbook. Maybe you can try MIT open course, after all, it's MIT!
https://ocw.mit.edu/courses/sloan-school-of-management/15-450-analytics-of-finance-fall-2010/lecture-notes/MIT15_450F10_lec02.pdf

**Comment by aryakarani** [comment]
Alright, Thank you TM, ofcourse Prof Andrew NG is the go to for Machine
Learning, I was looking for someone who might cover it with a quant trading
perspective.

Thanks and Regards,
Arya Karani.

**Comment by je-suis-tm** [comment]
Yeah, well, like I said, I learned a lot on the job, sorry I can't help you on this one. I would suggest you to work on a hackathon hosted by financial institutes. It may give you an idea on what you need to learn.

**Comment by aryakarani** [comment]
Alright, Thank you so much TM. Really appreciate all the help. I’ll start working on my own repo and was also planning to modify your work a bit and try and implement it for the Indian markets will keep you posted.

Thanks and best regards, 
Arya Karani.
